import 'package:auto_route/auto_route.dart';

import 'app_routes.gr.dart';
import 'auth_guard.dart';

@AutoRouterConfig()
class AppRouter extends $AppRouter {
  @override
  List<AutoRoute> get routes => [
        AutoRoute(page: SplashRoute.page,initial: true ),
        AutoRoute(page: UserLogin.page,),
        AutoRoute(page: UserSignup.page,),
        AutoRoute(page: SetUserProfile.page, guards: [AuthGuard()]),
        AutoRoute(page: ImageCapture.page, guards: [AuthGuard()]),
        AutoRoute(page: SaveImage.page, guards: [AuthGuard()]),
        AutoRoute(page: MainRoute.page, guards: [AuthGuard()]),
        AutoRoute(page: Home.page, guards: [AuthGuard()]),
        AutoRoute(page: Analytics.page, guards: [AuthGuard()]),
        AutoRoute(page: Settings.page, guards: [AuthGuard()]),
        AutoRoute(page: MyExpenses.page, guards: [AuthGuard()]),
        AutoRoute(page: Personal.page, guards: [AuthGuard()]),
        AutoRoute(page: AddIncome.page, guards: [AuthGuard()]),
        AutoRoute(page: UpdateIncome.page, guards: [AuthGuard()]),
        AutoRoute(page: AddExpense.page, guards: [AuthGuard()]),
        AutoRoute(page: MyIncomes.page, guards: [AuthGuard()]),
        AutoRoute(page: UpdateExpense.page, guards: [AuthGuard()]),
        AutoRoute(page: AddPersonalDiary.page, guards: [AuthGuard()]),
        AutoRoute(page: MyDiary.page, guards: [AuthGuard()]),
        AutoRoute(page: UpdatePersonalDiary.page, guards: [AuthGuard()]),
        AutoRoute(page: AddLeave.page, guards: [AuthGuard()]),
        AutoRoute(page: MyLeaves.page, guards: [AuthGuard()]),
        AutoRoute(page: UpdateLeave.page, guards: [AuthGuard()]),
        AutoRoute(page: AddMileage.page, guards: [AuthGuard()]),
        AutoRoute(page: MileageTracker.page, guards: [AuthGuard()]),
        AutoRoute(page: UpdateMileage.page, guards: [AuthGuard()]),
        AutoRoute(page: AddVehicle.page, guards: [AuthGuard()]),
        AutoRoute(page: MyGarage.page, guards: [AuthGuard()]),
        AutoRoute(page: UpdateVehicle.page, guards: [AuthGuard()]),
        AutoRoute(page: MyAccessory.page, guards: [AuthGuard()]),
        AutoRoute(page: AddAccessories.page, guards: [AuthGuard()]),
        AutoRoute(page: UpdateAccessories.page, guards: [AuthGuard()]),
        AutoRoute(page: ExpenseStats.page, guards: [AuthGuard()]),
        AutoRoute(page: IncomeStats.page, guards: [AuthGuard()]),
        AutoRoute(page: ExpenseAnalytics.page, guards: [AuthGuard()]),
        AutoRoute(page: IncomeAnalytics.page, guards: [AuthGuard()]),
        AutoRoute(page: YearAnalytics.page, guards: [AuthGuard()]),
        AutoRoute(page: LeaveAnalytics.page, guards: [AuthGuard()]),
        AutoRoute(page: FAQ.page, guards: [AuthGuard()]),
        AutoRoute(page: ContactUs.page, guards: [AuthGuard()]),
        AutoRoute(page: ContactSubmitted.page, guards: [AuthGuard()]),
        AutoRoute(page: HelpCentre.page, guards: [AuthGuard()]),
        AutoRoute(page: GiftVoucher.page, guards: [AuthGuard()]),
        AutoRoute(page: AboutUs.page, guards: [AuthGuard()]),
        AutoRoute(page: TermsAndConditions.page, guards: [AuthGuard()]),
        AutoRoute(page: UserProfile.page, guards: [AuthGuard()]),
        AutoRoute(page: UpdateUserProfile.page, guards: [AuthGuard()]),
        AutoRoute(page: AddPlan.page, guards: [AuthGuard()]),
        AutoRoute(page: UpdatePlan.page, guards: [AuthGuard()]),
        AutoRoute(page: ViewAllPlans.page, guards: [AuthGuard()]),
        AutoRoute(page: AddPlanExpense.page, guards: [AuthGuard()]),
        AutoRoute(page: UpdateExpensePlan.page, guards: [AuthGuard()]),
        AutoRoute(page: PlanExpenses.page, guards: [AuthGuard()]),
      ];
}
